name: Zero-Trust Security Shield

env:
  ENABLE_AI_CHECKOV: "true"
  ENABLE_AI_DOCKER: "true"
  ENABLE_AI_PACKAGES: "false"
  ENABLE_AI_GITLEAKS: "false"
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    name: DevSecOps AI Scan
    
    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4
        with:
          fetch-depth: 

      - name: Uruchomienie skanera i naprawy AI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Rozpoczynam skanowanie repozytorium Goof..."
          
          docker run --name ai-scanner \
            -e OPENAI_API_KEY=$OPENAI_API_KEY \
            -v ${{ github.workspace }}:/app/data \
            bartekmatyja/iac-sanity-checker:latest /app/data --min-severity LOW --generate-report || true
          
          docker cp ai-scanner:/app/security_audit_report.html ./security_audit_report.html
          
          EXIT_CODE=$(docker inspect ai-scanner --format='{{.State.ExitCode}}')
          
          exit $EXIT_CODE
            
      - name: Udostępnienie Raportu HTML
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: AI-Security-Report
          path: security_audit_report.html
